### ISSUE TITLE
vcに入ってない人は、曲のストップができるが、曲をスタートすることはできない

### ISSUE THREAD

**Issue by kinoko2k** [mtripg6666tdr/Discord-SimpleMusicBot#1559]
**バグを説明してください**
どのようなバグなのかを簡潔に説明してください。
VCに入ってない人は、曲の停止ができるが、曲の再生はできない。(害悪)

**再現手段**
どのようにしたときにバグが発生したか、またバグを再現する方法があれば説明してください。
1. vcで音楽を流しているチャンネルを見る。 (VCに入ってない)
2. embedについている、再生/一時停止ボタンを押す。 (VCに入ってない)
3. 一時停止はできる (VCに入ってない)
4. 再生ができない (VCに入ってない)

**Screenshots**
可能であれば、スクリーンショット等の参考になるデータを添付してください。
![image](https://user-images.githubusercontent.com/65443692/236445520-04491bc1-e7ad-4aa1-956b-c2b72659ab4b.png)

**環境**
問題が発生した時Discordの環境（スマホなのかなのか、バージョン等）、可能な場合にはbotのホスティング環境などを入力してください。
<バグを見つけたPC>
OS : Windows 10

<ホスト側>
OS : Ubuntu 22.04 LTS
Node.js : v18.16.0
bot : v4.0.4

**その他**
その他に参考になる情報があればご記入ください。

**Comment by mtripg6666tdr** [comment]
管理者は全ての権限をパイパスするようになっているのは仕様ですが、一般ユーザーでも同じ現象が起きますでしょうか？

**Comment by kinoko2k** [comment]
なるほど

**Comment by kinoko2k** [comment]
別垢で試してきます。

**Comment by kinoko2k** [comment]
![image](https://user-images.githubusercontent.com/65443692/236448683-1c914367-ecf2-4270-a630-2534da8d62e2.png)
別の人に頼んだところ、同じ現象が起きてます。

**Comment by kinoko2k** [comment]
![image](https://user-images.githubusercontent.com/65443692/236449048-e504c517-5c19-4860-ae86-75c482dab6d1.png)

**Comment by kinoko2k** [comment]
![image](https://user-images.githubusercontent.com/65443692/236449345-7250cb53-97f2-4f7c-b3ab-be6c76a9f37b.png)
![image](https://user-images.githubusercontent.com/65443692/236449373-91a3933e-c026-4de6-b5d1-424874858597.png)
頭出しも可能っぽいです。

**Comment by kinoko2k** [comment]
![image](https://user-images.githubusercontent.com/65443692/236450334-304709b7-1404-4fbd-bd40-7ca90d4c9a45.png)

**Comment by mtripg6666tdr** [comment]
少なくとも今の仕様としては、サーバーの管理権、チャンネルの管理権、そして管理者権限を持ってるユーザーが、権限の制限をバイパス出来るようになってます

**Comment by kinoko2k** [comment]
こっちの鯖が悪い気がしてきました。またなんか出たらまた言います。ご迷惑をおかけしました。

**Comment by mtripg6666tdr** [comment]
大丈夫です
むしろ歓迎です
引き続きよろしくお願いしますー

**Comment by kinoko2k** [comment]
と、思ってたんですが、
管理者が停止できることは確認しましたが、管理者が再生することはできないのですね...

**Comment by mtripg6666tdr** [comment]
それはそうですねー

**Comment by mtripg6666tdr** [comment]
現時点での仕様ですね

**Comment by mtripg6666tdr** [comment]
この件、大丈夫そうですかね？

**Comment by kinoko2k** [comment]
大丈夫です。対応ありがとうございます。
