### ISSUE TITLE
`mv` コマンドが正常に動かない

### ISSUE THREAD

**Issue by tubuanha** [mtripg6666tdr/Discord-SimpleMusicBot#186]
**バグを説明してください**
コマンドの使用方法は合っているはずだが、`✘音楽の再生中(および一時停止中)は移動元または移動先に0を指定することはできません。` と怒られる。

**再現手段**
キューが 121 曲の状態で `>mv 109 2` と実行した。

**Screenshots**
![Screenshot_20220228_030226](https://user-images.githubusercontent.com/70151015/155894143-e4e1f750-1dae-4ce0-a083-b11c9ba9d2c3.jpg)

**環境**
クライアント: Android 版 Ver.113.8
ホスト: OCI (Oracle Linux 8)

**その他**
特になし

**Comment by mtripg6666tdr** [comment]
Issueありがとうございました！ 🥳 
バグの内容を確認し修正いたしましたので、プル＆トランスパイルして修正されたことをご確認ください 😊。
万が一、まだそちらの環境でバグが残るようでしたら、再度オープンくださいますようお願いします。
