### ISSUE TITLE
DJという名前以外にVC操作ができるような機能

### ISSUE THREAD

**Issue by kinoko2k** [mtripg6666tdr/Discord-SimpleMusicBot#2137]
**新しい機能について説明してください**
DJという名前以外にVC操作ができるような感じでconfig.jsonでロールIDを設定することでDJ名じゃなくても操作ができるようにする機能

**Comment by mtripg6666tdr** [comment]
提案ありがとうございます!

**Comment by mtripg6666tdr** [comment]
ロールIDではなく名前一覧を指定する感じで実装を進めたいのですがいかがでしょうか？

**Comment by kinoko2k** [comment]
多分そちらのほうが他ユーザにもわかりやすいと思ったのでそのような方向でお願いします。

**Comment by mtripg6666tdr** [comment]
:tada: v4.2.0でリリースされました！
