### ISSUE TITLE
音声再生エンジンの移行

### ISSUE THREAD

**Issue by Fyphen1223** [mtripg6666tdr/Discord-SimpleMusicBot#2374]
音声再生エンジンをNode.jsで書かれている[NodeLink](https://github.com/PerformanC/NodeLink)に移行。Javaで書かれた[LavaLink](https://github.com/lavalink-devs/lavalink)もあるが統合がややこしい。

フレーム機能などはちょっとした工夫をしないと使えないのが問題。

シーク等は空白の時間を空けずに再生できる。

**Comment by mtripg6666tdr** [comment]
導入に手間がかかる依存関係を増やさないことがプロジェクトの目標にありますので、今後も当分は実装されることはないと思います

**Comment by mtripg6666tdr** [comment]
そもそも、このプロジェクトの目標は、データベースさえなくても、Node.jsさえあれば最低限動作する、シンプルなボットを構築することです。

NodeLink は初めて聞きましたが、LavaLink に関しては今までも何度か調査をしたことがあります。

LavaLinkは、JVM上で動作するように構築されたアプリですので、Node.jsなどに比べメモリ消費も大きいですし、別のプロセスとして動作する分、必要なリソースが増加すると考えられます。
また、LavaLinkの公開サーバーを用いるとしても、どこの誰がホストしているかもわからないサーバーを、コード上で固定するわけにいかず、`.env`などで指定する形になると思われます。この場合、新規でボットのセットアップをするユーザーは、自身が信頼するLavaLink サーバーを探すという手間が発生します。LavaLinkには英語のリソースが多く日本語のリソースが少ないという現状もあります。そのうえ、そもそも、サーバーを各自でホストしない限りは、LavaLinkサーバーのバックエンドのソースコードにいかなる変更が加えられているかもわからず、意図しない個人情報等の漏洩につながる可能性すらあります。

NodeLinkに関しては、今初めて知ったのですが、こちらは公開サーバーがなく、各自でサーバーを起動する必要がありそうです。これは、このコメントの冒頭で述べた本プロジェクトの趣旨に反してしまいます。

このような観点から、このプロジェクトでは、サーバーのデータ管理、キューの管理、音声に関するメタデータの取得、音声データのフェッチ、そして音声データの変換などを、すべてプロジェクト内で行っており、`discord-player`や`lavalink`といった外部の依存関係を極力省き、軽量でホストしやすい、そしてプロジェクト内での最適化をしやすい体制をとっています。
ご理解いただけますと幸いです。

LavaLinkなどの外部ソフトウェアを使用しないことによる、機能の不足、ご指摘いただきました遅延の多さなどに関しましては、こちらのプロジェクト内でできる限りの改善を検討していきます。このほかにも機能の要望などがございましたら、個別にissueを開いていただきますようお願いいたします。
