### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by kinoko2k** [mtripg6666tdr/Discord-SimpleMusicBot#73]
**バグを説明してください**
どのようなバグなのかを簡潔に説明してください。
.mdの誤字
**再現手段**
どのようにしたときにバグが発生したか、またバグを再現する方法があれば説明してください。
見たとき
**Screenshots**
可能であれば、スクリーンショット等の参考になるデータを添付してください。
![image](https://user-images.githubusercontent.com/65443692/134491078-aba9a141-8e14-4362-ad30-13c282378082.png)
**環境**
問題が発生した時Discordの環境（スマホなのかなのか、バージョン等）、可能な場合にはbotのホスティング環境などを入力してください。
PC
**その他**
その他に参考になる情報があればご記入ください。

**Comment by mtripg6666tdr** [comment]
Isseuありがとうございます！
確認し修正いたしました！
ご確認くださいますようお願いします！
