### ISSUE TITLE
ボイスチャンネルに参加しなくても `search` コマンドが使える

### ISSUE THREAD

**Issue by Khsmty** [mtripg6666tdr/Discord-SimpleMusicBot#889]
**バグを説明してください**
ボイスチャンネルに参加していない状態で `>search` コマンドを実行すると、「ボイスチャンネルに参加してからコマンドを送信してください:relieved:」と返信されるにも関わらず、検索が実行できてしまう。

**再現手段**
ボイスチャンネルに参加していない状態で `>search` コマンドを実行する

**Screenshots**
![B9F3075D-80F4-4E18-B07B-B823A343E7AD](https://user-images.githubusercontent.com/70151015/215323169-36d4cd36-d54b-448d-9fbc-5f7c5fe70d2f.jpeg)

<!-- **環境**
問題が発生した時Discordの環境（スマホなのかなのか、バージョン等）、可能な場合にはbotのホスティング環境などを入力してください。

**その他**
その他に参考になる情報があればご記入ください。—->

**Comment by mtripg6666tdr** [comment]
現在これは仕様です

**Comment by mtripg6666tdr** [comment]
おそらくボットが音楽を再生している状況では、VCに参加していないほかのユーザーが検索コマンドを実行することはできないと思うのですが（一応これが仕様）いかがでしょうか？

**Comment by Khsmty** [comment]
なるほど、仕様でしたか
確かにそのような挙動になりました。ありがとうございます。

**Comment by mtripg6666tdr** [comment]
たしかに分かりにくい気がするので、近日中にドキュメントに追記しますね、
